### ISSUE TITLE
Compatibilidade com tds-vscode?

### ISSUE THREAD

**Issue by cicerocruz** [totvs/totvs-healthcare-dev#3]
Olá este componente pode ser usado com o tds-vscode?

**Comment by ezequielgandolfi** [comment]
@cicerocruz Não teria problema rodar em conjunto com o tds-vscode, mas as funcionalidades deste plugin estão muito atreladas a processos específicos da unidade de Caxias do Sul.
Se busca suporte para OpenEdge, recomendo testar um destes plugins:
https://marketplace.visualstudio.com/items?itemName=EzequielGandolfi.openedge-zext
https://marketplace.visualstudio.com/items?itemName=rafaelcanal.gps-abl
